# Generated by Django 3.1.3 on 2020-11-10 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
                ('email', models.EmailField(db_index=True, max_length=200, unique=True)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=2048)),
                ('brand', models.CharField(db_index=True, max_length=200)),
                ('review_score', models.DecimalField(decimal_places=2, max_digits=10, max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='FavoriteList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='favorites_list.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='favorites_list.product')),
            ],
            options={
                'db_table': 'favorites_list',
                'unique_together': {('product', 'client')},
            },
        ),
        migrations.AddField(
            model_name='client',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', through='favorites_list.FavoriteList', to='favorites_list.Product'),
        ),
    ]
