# Generated by Django 3.1.3 on 2020-11-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=2048)),
                ('brand', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('reviewScore', models.DecimalField(decimal_places=2, max_digits=2, max_length=200)),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
