# Generated by Django 3.1.3 on 2020-11-10 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_list', '0002_auto_20201110_0200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritelist',
            options={'managed': False},
        ),
    ]
