# Generated by Django 3.1.3 on 2020-11-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_list', '0003_auto_20201108_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritelist',
            name='list_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='review_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=200),
        ),
    ]
